/** @format */

import { Container, Grid } from '@mui/material';
import Head from 'next/head';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Container>
				<Grid container spacing={2}>
					<Grid item lg={8}>
						{/* <ProfileCard />
						<RecordsCard />
						<ContributionTabs /> */}
					</Grid>
				</Grid>
			</Container>
		</>
	);
}
