/** @format */

import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import Container from '@mui/material/Container';
import fetchMember from '../Fetcher/OireachtasAPI/member';
import { member } from '../Models/UI/member';
import fetchParties from '../Fetcher/OireachtasAPI/parties';
import fetchConstituencies from '../Fetcher/OireachtasAPI/constituencies';

export default function Home(props: {
	members: JSON[];
	parties: JSON[];
	constits: JSON[];
}) {
	let members: member[] = JSON.parse(props.members.toString()).filter(
		(m: { cessation: null }) => m.cessation == (undefined || null)
	);
	const name = '33rd Dáil';
	// let parties = JSON.parse(props.parties);
	console.log(props.constits);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Container>
				{/* <IndexLayout
					name={name}
					members={members}
					parties={props.parties}
					constits={props.constits}
				/> */}
			</Container>
		</>
	);
}

/** @format */

export const getStaticProps: GetStaticProps = async () => {
	const members = await fetchMember({
		houseNo: 33,
		serialized: true,
	});

	const parties = await fetchParties({
		chamber: 'dail',
		houseNo: 33,
	});

	const constits = await fetchConstituencies({ chamber: 'dail', houseNo: 33 });

	return {
		props: {
			members: members,
			parties: parties,
			constits: constits,
		},
		revalidate: 43200, // 12 hours
	};
};
